### ISSUE TITLE
3.4 Puppet Enterprise Compatibility 

### ISSUE THREAD

**Issue by acidprime** [binford2k/fingerpuppet#2]
As PE 3.4 will moving to a jvm master, anything that relies on openssl may break as native c extentions are not supported in the jvm. See PE-5664 (internal). I have been told that at least one client has a function that calls your code directly.

**Comment by binford2k** [comment]
Like a puppet function that requires this as a library? Whoa

**Comment by acidprime** [comment]
Yeah I think that at the point you needed to call this , the person in question could have just used the http pool directly which will keep working in thw jvm. I will see I can trackdown the PSE who said they deployed this and have them update with an example.

**Comment by acidprime** [comment]
This ended up being a non - issue as we ship the required ssl libraries for pe-java but does still effect FOSS
